export const fileNames = {
  javascript: "index.js",
  python: "main.py",
  java: "Main.java",
  c: "main.c", // C
  cpp: "main.cpp", // C++
  cs: "Program.cs", // C#
  typescript: "index.ts",
  go: "main.go",
  php: "index.php",
  ruby: "main.rb",
  swift: "main.swift",
  kotlin: "Main.kt",
  rust: "main.rs",
  r: "main.r",
  perl: "main.pl",
  bash: "main.sh",
  dart: "main.dart",
  scala: "Main.scala",
  sql: "main.sql",
  html: "index.html",
  css: "styles.css",
  json: "data.json",
  xml: "data.xml",
  markdown: "README.md",
  yaml: "config.yaml",
};

export const starterCodes = {
  javascript: `// index.js\nconsole.log("Hello, JavaScript!");`,
  python: `# main.py\nprint("Hello, Python!")`,
  java: `// Main.java\npublic class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello, Java!");\n  }\n}`,
  c: `// main.c\n#include <stdio.h>\nint main() {\n  printf("Hello, C!\\n");\n  return 0;\n}`,
  cpp: `// main.cpp\n#include<iostream>\nusing namespace std;\nint main() {\n  cout << "Hello, C++!" << endl;\n  return 0;\n}`,
  cs: `// Program.cs\nusing System;\nclass Program {\n  static void Main() {\n    Console.WriteLine("Hello, C#!");\n  }\n}`,
  typescript: `// index.ts\nconsole.log("Hello, TypeScript!");`,
  go: `// main.go\npackage main\n\nimport "fmt"\n\nfunc main() {\n  fmt.Println("Hello, Go!")\n}`,
  php: `// index.php\n<?php\necho "Hello, PHP!";`,
  ruby: `# main.rb\nputs "Hello, Ruby!"`,
  swift: `// main.swift\nprint("Hello, Swift!")`,
  kotlin: `// Main.kt\nfun main() {\n  println("Hello, Kotlin!")\n}`,
  rust: `// main.rs\nfn main() {\n  println!("Hello, Rust!");\n}`,
  r: `# main.r\nprint("Hello, R!")`,
  perl: `# main.pl\nprint "Hello, Perl!\\n";`,
  bash: `# main.sh\necho "Hello, Bash!"`,
  dart: `// main.dart\nvoid main() {\n  print("Hello, Dart!");\n}`,
  scala: `// Main.scala\nobject Main {\n  def main(args: Array[String]): Unit = {\n    println("Hello, Scala!")\n  }\n}`,
  sql: `-- main.sql\nSELECT "Hello, SQL!" AS message;`,
  html: `<!-- index.html -->\n<!DOCTYPE html>\n<html>\n<head><title>Hello</title></head>\n<body>\n  <h1>Hello, HTML!</h1>\n</body>\n</html>`,
  css: `/* styles.css */\nbody {\n  background-color: #f0f0f0;\n  color: #333;\n}`,
  json: `// data.json\n{\n  "message": "Hello, JSON!"\n}`,
  xml: `<!-- data.xml -->\n<message>Hello, XML!</message>`,
  markdown: `# README.md\n\nHello, Markdown!`,
  yaml: `# config.yaml\nmessage: "Hello, YAML!"`,
};
